# Generated by Django 3.1.7 on 2021-03-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField()),
                ('price', models.FloatField(verbose_name=26.99)),
                ('reason', models.CharField(max_length=100)),
            ],
        ),
    ]
