# Generated by Django 3.1.7 on 2021-03-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210303_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominio',
            name='available',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='dominio',
            name='reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
