# Generated by Django 3.1.7 on 2021-03-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210303_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominio',
            name='available',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
