# Generated by Django 3.1.7 on 2021-03-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210303_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominio',
            name='dominio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
