# Generated by Django 3.1.7 on 2021-03-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210303_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominio',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
